import { useState } from 'react'
import { Link } from 'react-router-dom'
import { API } from '../api.js'
import { useAuth } from '../context/AuthContext.jsx'

function exportCSV(collection) { const content = API.exportCSV(collection); const url = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `cput-home-${collection}.csv`; anchor.click(); URL.revokeObjectURL(url) }

export default function Admin() {
  const { user } = useAuth(); const [tab, setTab] = useState('listings'); const [announcement, setAnnouncement] = useState(''); const [notice, setNotice] = useState(''); const [, tick] = useState(0); const refresh = () => tick(value => value + 1)
  const all = API.listings(); const users = API.users().filter(item => item.role !== 'admin'); const applications = API.applications(); const reports = API.reports(); const providers = users.filter(item => item.role === 'landlord');
  const act = (description, action) => { action(); API.audit(description, user.email); setNotice(description); refresh() }
  const approveListing = listing => act(`Approved listing #${listing.id}`, () => API.updateListing(listing.id, { status: 'approved' }))
  const rejectListing = listing => { const reason = window.prompt('Reason for rejecting this listing'); if (reason) act(`Rejected listing #${listing.id}: ${reason}`, () => API.updateListing(listing.id, { status: 'rejected', rejectionReason: reason })) }
  const rejectProvider = provider => { const reason = window.prompt('Reason for rejecting provider'); if (reason) act(`Rejected provider ${provider.email}: ${reason}`, () => API.setUserStatus(provider.email, 'rejected')) }
  const bars = ['Bellville', 'Cape Town / District Six', 'Mowbray', 'Wellington', 'Athlone', 'Granger Bay'].map(campus => ({ campus, count: all.filter(listing => listing.campus === campus || listing.location === campus).length }))
  const max = Math.max(1, ...bars.map(item => item.count))
  const publish = event => { event.preventDefault(); if (announcement.trim()) act('Published announcement', () => API.announce(announcement.trim())); setAnnouncement('') }

  return <>
    <div className="role-banner admin-banner"><div className="page-heading"><div><p className="eyebrow">MODERATION</p><h1>Admin console</h1></div><div className="row"><button className="btn alt sm" onClick={() => exportCSV('listings')}>Export listings CSV</button><button className="btn alt sm" onClick={() => exportCSV('applications')}>Export applications CSV</button></div></div></div>
    <div className="stats"><div className="stat"><b>{all.filter(item => item.status === 'pending').length}</b>Listing reviews</div><div className="stat"><b>{providers.filter(item => item.status === 'pending-verification').length}</b>Provider checks</div><div className="stat"><b>{reports.filter(item => item.status === 'open').length}</b>Open reports</div><div className="stat"><b>{applications.length}</b>Applications</div><div className="stat"><b>{all.filter(item => item.emergency).length}</b>Emergency flags</div></div>
    <div className="tabs">{['listings', 'providers', 'reports', 'users', 'analytics', 'audit'].map(item => <button key={item} className={`btn sm ${tab === item ? 'on' : ''}`} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'listings' && <section className="panel tblwrap"><h2>Listing verification queue</h2><table className="tbl"><thead><tr><th>Listing</th><th>Provider</th><th>Campus / rent</th><th>Status</th><th>Actions</th></tr></thead><tbody>{all.map(listing => <tr key={listing.id}><td><Link to={`/listing/${listing.id}`}>{listing.title}</Link>{listing.sample && <small className="block muted">Sample data; independently verify</small>}</td><td>{listing.owner}</td><td>{listing.campus} · R{listing.price}</td><td><span className="badge">{listing.status}</span>{listing.rejectionReason && <small className="block">{listing.rejectionReason}</small>}</td><td><div className="row"><button className="btn green sm" onClick={() => approveListing(listing)}>Approve</button><button className="btn alt sm" onClick={() => rejectListing(listing)}>Reject with reason</button><button className="btn red sm" onClick={() => act(`Removed listing #${listing.id}`, () => API.removeListing(listing.id))}>Remove</button></div></td></tr>)}</tbody></table></section>}
    {tab === 'providers' && <section className="panel tblwrap"><h2>Landlords and accreditation</h2><table className="tbl"><thead><tr><th>Provider</th><th>Verification</th><th>Accreditation claim</th><th>Actions</th></tr></thead><tbody>{providers.map(provider => <tr key={provider.email}><td>{provider.name}<small className="block muted">{provider.email} · {provider.registrationNumber || 'No company/ID number'}</small></td><td>{provider.status}</td><td>{provider.accreditation ? 'CPUT accredited' : 'Not accredited'}</td><td><div className="row"><button className="btn green sm" onClick={() => act(`Verified provider ${provider.email}`, () => API.setUserStatus(provider.email, 'verified'))}>Verify</button><button className="btn alt sm" onClick={() => act(`Updated accreditation for ${provider.email}`, () => API.setAccreditation(provider.email, !provider.accreditation))}>{provider.accreditation ? 'Remove accreditation' : 'Mark accredited'}</button><button className="btn red sm" onClick={() => rejectProvider(provider)}>Reject</button></div></td></tr>)}</tbody></table></section>}
    {tab === 'reports' && <section className="panel tblwrap"><h2>Fraud and misleading-listing reports</h2>{reports.length ? <table className="tbl"><thead><tr><th>Listing</th><th>Reporter</th><th>Reason</th><th>Queue</th><th></th></tr></thead><tbody>{reports.map(report => <tr key={report.id}><td><Link to={`/listing/${report.listingId}`}>{API.listing(report.listingId)?.title || `Listing ${report.listingId}`}</Link></td><td>{report.reporter}</td><td>{report.reason}</td><td>{report.status}</td><td><button className="btn alt sm" onClick={() => act(`Resolved report #${report.id}`, () => API.resolveReport(report.id, 'resolved'))}>Resolve</button></td></tr>)}</tbody></table> : <p className="muted">No user reports submitted.</p>}</section>}
    {tab === 'users' && <section className="panel tblwrap"><h2>User management</h2><table className="tbl"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(item => <tr key={item.email}><td>{item.name}<small className="block muted">{item.email}</small></td><td>{item.role}</td><td>{item.status}</td><td><div className="row"><button className="btn alt sm" onClick={() => act(`Changed account status for ${item.email}`, () => API.setUserStatus(item.email, item.status === 'suspended' ? 'verified' : 'suspended'))}>{item.status === 'suspended' ? 'Restore' : 'Suspend'}</button><button className="btn red sm" onClick={() => { if (window.confirm(`Remove ${item.email}?`)) act(`Removed user ${item.email}`, () => API.removeUser(item.email)) }}>Remove</button></div></td></tr>)}</tbody></table></section>}
    {tab === 'analytics' && <>
      <section className="panel"><h2>Sample listings by campus</h2><div className="bar-chart">{bars.map(item => <div className="bar-row" key={item.campus}><span>{item.campus}</span><div className="bar-track"><div className="bar-fill" style={{ width: `${item.count / max * 100}%` }} /></div><b>{item.count}</b></div>)}</div></section>
      <section className="panel"><h2>Applications over time</h2><div className="mini-chart" aria-label="Applications by month">{Array.from({ length: 6 }, (_, index) => { const month = new Date(); month.setMonth(month.getMonth() - 5 + index); const count = applications.filter(application => new Date(application.createdAt).getMonth() === month.getMonth()).length; return <div key={index}><i style={{ height: `${Math.max(8, count * 24)}px` }} /><span>{month.toLocaleString('en', { month: 'short' })}</span><b>{count}</b></div> })}</div><p>Emergency listings: {all.filter(item => item.emergency).length}</p></section>
    </>}
    {tab === 'audit' && <><section className="panel"><h2>Announcements</h2><form className="row" onSubmit={publish}><label className="grow">Message to all users<input value={announcement} onChange={event => setAnnouncement(event.target.value)} /></label><button className="btn">Publish</button></form></section><section className="panel"><h2>Admin audit log</h2>{API.auditLog().slice().reverse().map(item => <p key={item.id}>{new Date(item.at).toLocaleString()} · {item.actor} · {item.action}</p>)}{!API.auditLog().length && <p className="muted">No admin actions recorded yet.</p>}</section></>}
    {notice && <p role="status" className="status-note">{notice}</p>}
  </>
}